frontend:
  image: zhangrui20200722/hello-flask
  tag: '134202c'
  autoscaling:
    averageUtilization: 90
backend:
  image: zhangrui20200722/hello-flask
  tag: '134202c'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  
